GET http://localhost:8000/api/auth/profile HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODAwMFwvYXBpXC9hdXRoXC9sb2dpbiIsImlhdCI6MTYwNjI1MDE5MiwiZXhwIjoxNjA2MjUzNzkyLCJuYmYiOjE2MDYyNTAxOTIsImp0aSI6IjVyek4xVEZPQVZmbmxDVGUiLCJzdWIiOjIsInBydiI6ImY3MTZiM2UwNDY3YTBhZmY0YmQ4ZWQ2ZDk0NzZmZTY5NzUwYTMzY2UifQ.0PbsoNLqaLAcJ6-8ka1uIMo7Qi7YZHQGRMOHvvOKTAA
